on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13.2
        env:
          POSTGRES_PASSWORD: password

    steps:
    - uses: actions/checkout@v2

    - name: PHP Security Checker
      uses: StephaneBour/actions-php-security-checker@1.1
      with:
        composer-lock: './composer.lock'

    - name: Setup project
      run: make setup
      env:
        DB_HOST: localhost

    - name: Check lint
      run: make lint

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: make test